name: Docker Image CI for GHCR

on: push

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.KirthivasanPN-hash }}
          password: ${{ secrets.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}}

  build_and_publish:
    runs-on: ubuntu-latest
    needs: login
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and push the image
        run: |
          docker build -t ghcr.io/kirpandu/arithmetic-service:latest --file Dockerfile .
          docker push ghcr.io/kirpandu/arithmetic-service:latest
